@refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5fZG9lIiwiaWF0IjoxNzMzODI0MDMzLCJleHAiOjE3MzQ0Mjg4MzN9.pkOr1chPgcmu3EKK4Px84-wAI8EbmEcVvI-c5IAShr8
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5fZG9lIiwiaWF0IjoxNzMzODMwMzc3LCJleHAiOjE3MzM4MzA0Mzd9.osz8LSBOi8aInhKSt-Mg1NnkWeo68cCApC_M69LnYWg
### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "john_doe",
  "password": "123456"
}


### Refresh Token
POST http://localhost:3000/auth/refresh
Content-Type: application/json
Authorization: Bearer {{refreshToken}}

### Get All Personal Data
GET http://localhost:3000/personaldata
Authorization: Bearer {{accessToken}}

### Get Personal Data by ID
GET http://localhost:3000/personaldata/1
Authorization: Bearer {{accessToken}}

### Create New Personal Data
POST http://localhost:3000/personaldata
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "id": 3,
  "name": "Sam Smith",
  "email": "sam@example.com"
}

### Update Personal Data by ID
PUT http://localhost:3000/personaldata/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "John Doe Updated",
  "email": "johnupdated@example.com"
}

### Delete Personal Data by ID
DELETE http://localhost:3000/personaldata/4
Authorization: Bearer {{accessToken}}


